// Code generated by goctl. DO NOT EDIT.
package types

import "github.com/jinzhu/gorm"

type Req struct {
}

type Res struct {
}

type RoleInfo struct {
	RoleName string `json:"roleName"`
	Value    string `json:"value"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginRes struct {
	Roles    []RoleInfo `json:"roles"`
	UserId   string     `json:"userId"`
	Username string     `json:"username"`
	Token    string     `json:"token"`
	RealName string     `json:"realName"`
	Desc     string     `json:"desc"`
}

type GetUserInfoReq struct {
	T string `form:"_t"`
}

type GetUserInfoRes struct {
	UserId   string     `json:"userId"`
	Username string     `json:"username"`
	RealName string     `json:"realName"`
	Avatar   string     `json:"avatar"`
	Desc     string     `json:"desc"`
	Password string     `json:"password"`
	Token    string     `json:"token"`
	HomePath string     `json:"homePath"`
	Roles    []RoleInfo `json:"roles"`
}

type DvrReq struct {
	Action   string `json:"action"`
	ClientId int    `json:"client_id"`
	Ip       string `json:"ip"`
	Vhost    string `json:"vhost"`
	App      string `json:"app"`
	Stream   string `json:"stream"`
	Param    string `json:"param"`
	Cwd      string `json:"cwd"`
	File     string `json:"file"`
}

type Dvr struct {
	gorm.Model  `json:"-,optional"`
	ClientId    int    `json:"client_id"`
	Ip          string `json:"ip"`
	Vhost       string `json:"vhost"`
	App         string `json:"app"`
	Stream      string `json:"stream"`
	Param       string `json:"param"`
	Cwd         string `json:"cwd"`
	File        string `json:"file"`
	Base        string `json:"base"`
	ContentName string `json:"content_name"`
}

type DvrRes struct {
	ErrorCode int `json:"error_code"`
}
