// Code generated by goctl. DO NOT EDIT.
package types

import "github.com/jinzhu/gorm"

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type RoleInfo struct {
	RoleName string `json:"roleName"`
	Value    string `json:"value"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Roles    []RoleInfo `json:"roles"`
	UserId   string     `json:"userId"`
	Username string     `json:"username"`
	Token    string     `json:"token"`
	RealName string     `json:"realName"`
	Desc     string     `json:"desc"`
}

type DvrRequest struct {
	Action   string `json:"action"`
	ClientId int    `json:"client_id"`
	Ip       string `json:"ip"`
	Vhost    string `json:"vhost"`
	App      string `json:"app"`
	Stream   string `json:"stream"`
	Param    string `json:"param"`
	Cwd      string `json:"cwd"`
	File     string `json:"file"`
}

type Dvr struct {
	gorm.Model  `json:"-,optional"`
	ClientId    int    `json:"client_id"`
	Ip          string `json:"ip"`
	Vhost       string `json:"vhost"`
	App         string `json:"app"`
	Stream      string `json:"stream"`
	Param       string `json:"param"`
	Cwd         string `json:"cwd"`
	File        string `json:"file"`
	Base        string `json:"base"`
	ContentName string `json:"content_name"`
}

type DvrResponse struct {
	ErrorCode int `json:"error_code"`
}
