[postgres]
host = "192.168.13.241"
port = 5432
username = "postgres"
password = "g2ulA2yNc"
db = "agent"
schema = "agent"


[ssh]
host = "192.168.10.252"
port = 22
user = "root"
password = "certusnet@2020"


[dvr]
path = "/root/nfs/live"
delete = true


[minio]
endpoint = "192.168.13.241:9000"
accessKeyID = "minio"
secretAccessKey = "minio123"


[stream]
server = "rtmp://192.168.10.252:31857/live"
