// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"StreamAgent/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/srs/dvr",
				Handler: DvrHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/getUserInfo",
				Handler: GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/logout",
				Handler: LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/stream/start",
				Handler: StartStreamHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/stream/stop",
				Handler: StopStreamHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/srs/onConnect",
				Handler: VerifyConnectStreamHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/srs/onPush",
				Handler: VerifyPushStreamHandler(serverCtx),
			},
		},
	)
}
